//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourDay.Site {
    
    
    public partial class ContractorCabinet {
        
        /// <summary>
        /// MenuSimple1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Navigate.CategoriesMenuSimple MenuSimple1;
        
        /// <summary>
        /// ContractorCabinetUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Contractor.ContractorCabinetUC ContractorCabinetUC1;
    }
}
