//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourDay.Site {
    
    
    public partial class Default {
        
        /// <summary>
        /// WayToEventCard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Default.WayToEventCard WayToEventCard1;
        
        /// <summary>
        /// EventCardCreator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.EventCard.EventCardCreator EventCardCreator1;
        
        /// <summary>
        /// CategoriesMenuSimpleItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Navigate.CategoriesMenuSimple CategoriesMenuSimpleItem;
        
        /// <summary>
        /// PromoBlock1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Default.PromoBlock PromoBlock1;
        
        /// <summary>
        /// BestContractors1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Default.BestContractors BestContractors1;
        
        /// <summary>
        /// EventsReports1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Default.EventsReports EventsReports1;
    }
}
