ALTER TABLE [dbo].[ContractorCategories]
    ADD CONSTRAINT [PK_ContractorCategories] PRIMARY KEY CLUSTERED ([ContractorId] ASC, [SubcategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

