ALTER TABLE [dbo].[EventCardCompany]
    ADD CONSTRAINT [PK_EventCardCompany] PRIMARY KEY NONCLUSTERED ([EventCardId] ASC, [ContractorId] ASC, [SubcategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

