//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourDay.Site.Controls.EventCard {
    
    
    public partial class EventCardBody {
        
        /// <summary>
        /// ContractorsListConcerned control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.EventCard.ContractorsList ContractorsListConcerned;
        
        /// <summary>
        /// ContractorsListAccepted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.EventCard.ContractorsList ContractorsListAccepted;
        
        /// <summary>
        /// LabelPhotoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelPhotoes;
        
        /// <summary>
        /// Photoes1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YourDay.Site.Controls.Common.Photoes Photoes1;
    }
}
